# Generated by Django 4.2.3 on 2023-07-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类标签')),
            ],
            options={
                'verbose_name': '小说分类',
                'verbose_name_plural': '小说分类',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户姓名')),
                ('xsbh', models.CharField(max_length=50, verbose_name='小说编号')),
                ('name', models.CharField(max_length=50, verbose_name='小说名称')),
                ('sfgm', models.CharField(max_length=50, verbose_name='是否购买')),
            ],
            options={
                'verbose_name': '购买信息',
                'verbose_name_plural': '购买信息',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128, verbose_name='姓名')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=254, verbose_name='邮箱地址')),
                ('yhqx', models.CharField(blank=True, max_length=20, verbose_name='用户权限')),
                ('qq', models.CharField(blank=True, max_length=20, verbose_name='用户的QQ号码')),
                ('weChat', models.CharField(blank=True, max_length=20, verbose_name='用户的微信号码')),
                ('mobile', models.CharField(blank=True, max_length=25, verbose_name='用户的手机号码')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=8, verbose_name='性别')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=200, verbose_name='小说编号')),
                ('name', models.CharField(max_length=200, verbose_name='小说名')),
                ('singer', models.CharField(max_length=200, verbose_name='作者')),
                ('type', models.CharField(max_length=200, verbose_name='分类')),
                ('zjnum', models.CharField(max_length=200, verbose_name='章节数量')),
                ('zjtitle', models.CharField(max_length=200, verbose_name='章节标题')),
                ('xsbh', models.CharField(max_length=200, verbose_name='章节编号')),
                ('img', models.FileField(upload_to='noveimage/', verbose_name='封面')),
                ('file', models.FileField(upload_to='novefile/', verbose_name='文章路径')),
                ('label_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.label', verbose_name='分类')),
            ],
            options={
                'verbose_name': '小说信息',
                'verbose_name_plural': '小说信息',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lwxh', models.IntegerField(default=0, verbose_name='礼物鲜花数量')),
                ('lwkf', models.IntegerField(default=0, verbose_name='礼物咖啡数量')),
                ('lwzs', models.IntegerField(default=0, verbose_name='礼物钻石数量')),
                ('lwhc', models.IntegerField(default=0, verbose_name='礼物豪车数量')),
                ('tjsl', models.IntegerField(default=0, verbose_name='推荐数量')),
                ('ypsl', models.IntegerField(default=0, verbose_name='月票数量')),
                ('novel_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.novel', verbose_name='小说名')),
            ],
            options={
                'verbose_name': '小说动态',
                'verbose_name_plural': '小说动态',
            },
        ),
    ]
