# Generated by Django 4.2.3 on 2023-07-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='lwhc',
            field=models.IntegerField(default=0, verbose_name='礼物数量'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='lwkf',
            field=models.IntegerField(default=0, verbose_name='下载数量'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='lwxh',
            field=models.IntegerField(default=0, verbose_name='阅读数量'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='lwzs',
            field=models.IntegerField(default=0, verbose_name='购买数量'),
        ),
    ]
