# Generated by Django 4.2.3 on 2023-07-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_dynamic_lwhc_alter_dynamic_lwkf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='bookid',
            field=models.CharField(default='', max_length=20, verbose_name='小说编号'),
        ),
    ]
