# Generated by Django 4.2.3 on 2023-07-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_dynamic_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='iswj',
            field=models.CharField(default='是', max_length=20, verbose_name='是否完结'),
        ),
    ]
