# Generated by Django 4.2.3 on 2023-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_novel_iswj'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='fbrq',
            field=models.CharField(default='', max_length=20, verbose_name='发布日期'),
        ),
    ]
