# Generated by Django 4.2.3 on 2023-07-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_novel_fbrq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户姓名')),
                ('bookid', models.CharField(max_length=50, verbose_name='小说编号')),
                ('name', models.CharField(max_length=50, verbose_name='小说名称')),
                ('plrq', models.CharField(max_length=50, verbose_name='评论日期')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
            },
        ),
    ]
