# Generated by Django 4.2.3 on 2023-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_dynamic_novel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户姓名')),
                ('xsbh', models.CharField(max_length=50, verbose_name='小说编号')),
                ('name', models.CharField(max_length=50, verbose_name='小说名称')),
                ('ydzj', models.CharField(max_length=50, verbose_name='阅读章节')),
                ('ydid', models.CharField(max_length=50, verbose_name='阅读的小说id')),
                ('xszj', models.CharField(max_length=50, verbose_name='小说章节')),
                ('sfwj', models.CharField(max_length=50, verbose_name='是否完结')),
                ('type', models.CharField(max_length=50, verbose_name='小说类型')),
            ],
            options={
                'verbose_name': '阅读信息',
                'verbose_name_plural': '阅读信息',
            },
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ['bookid'], 'verbose_name': '小说信息', 'verbose_name_plural': '小说信息'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='gmrq',
            field=models.CharField(default='', max_length=50, verbose_name='购买日期'),
        ),
    ]
