# Generated by Django 4.2.3 on 2023-08-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_read_alter_novel_options_purchase_gmrq'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='xjsl',
            field=models.IntegerField(default=0, verbose_name='星级数量'),
        ),
    ]
