# Generated by Django 4.2.3 on 2023-08-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_dynamic_xjsl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xsxjpj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户姓名')),
                ('xsbh', models.CharField(max_length=50, verbose_name='小说编号')),
                ('xjsl', models.IntegerField(default=0, verbose_name='星级数量')),
                ('pjrq', models.CharField(max_length=50, verbose_name='评价日期')),
            ],
            options={
                'verbose_name': '小说评星',
                'verbose_name_plural': '小说评星',
            },
        ),
    ]
