# Generated by Django 4.1.8 on 2024-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_xsxjpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TP01', models.CharField(max_length=50, verbose_name='货物编号')),
                ('TP02', models.CharField(max_length=50, verbose_name='承运商编号')),
                ('TP03', models.CharField(max_length=50, verbose_name='承运人名称')),
                ('TP04', models.IntegerField(max_length=50, verbose_name='拖车')),
                ('TP05', models.CharField(max_length=50, verbose_name='司机')),
                ('TP06', models.CharField(max_length=50, verbose_name='司机电话')),
                ('TP07', models.CharField(max_length=400, verbose_name='始发站')),
                ('TP08', models.CharField(max_length=400, verbose_name='目的站')),
                ('TP09', models.CharField(max_length=25, verbose_name='发货日期')),
                ('TP10', models.CharField(max_length=25, verbose_name='操作日期')),
                ('TP11', models.CharField(max_length=50, verbose_name='操作人')),
                ('TP12', models.CharField(max_length=200, verbose_name='备注')),
                ('TP13', models.CharField(max_length=200, verbose_name='备用字段一')),
                ('TP14', models.CharField(max_length=200, verbose_name='备用字段一')),
                ('TP15', models.CharField(max_length=200, verbose_name='备用字段一')),
                ('TP16', models.CharField(max_length=200, verbose_name='备用字段一')),
                ('TP17', models.CharField(max_length=200, verbose_name='备用字段一')),
                ('TP18', models.CharField(max_length=200, verbose_name='备用字段一')),
                ('TP19', models.CharField(max_length=200, verbose_name='备用字段一')),
                ('TP20', models.CharField(max_length=200, verbose_name='备用字段一')),
            ],
            options={
                'verbose_name': '物流轨迹信息',
                'verbose_name_plural': '物流轨迹',
            },
        ),
    ]
