# Generated by Django 4.1.8 on 2024-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='TP04',
            field=models.CharField(max_length=50, verbose_name='拖车'),
        ),
    ]
