# Generated by Django 4.1.8 on 2024-06-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_transport_tp04'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logisticstrajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LP01', models.CharField(max_length=50, verbose_name='货物编号')),
                ('LP02', models.CharField(max_length=50, verbose_name='承运商编号')),
                ('LP03', models.CharField(max_length=50, verbose_name='起点经度')),
                ('LP04', models.CharField(max_length=400, verbose_name='起点地址')),
                ('LP05', models.CharField(max_length=50, verbose_name='行驶距离')),
                ('LP06', models.CharField(max_length=50, verbose_name='行驶用时')),
                ('LP07', models.CharField(max_length=50, verbose_name='抵达时间')),
                ('LP08', models.CharField(max_length=50, verbose_name='终点经纬度')),
                ('LP09', models.CharField(max_length=400, verbose_name='终点经地址')),
                ('LP10', models.CharField(max_length=50, verbose_name='备用字段')),
                ('LP11', models.CharField(max_length=50, verbose_name='备用字段')),
                ('LP12', models.CharField(max_length=50, verbose_name='备用字段')),
                ('LP13', models.CharField(max_length=50, verbose_name='备用字段')),
                ('LP14', models.CharField(max_length=50, verbose_name='备用字段')),
                ('LP15', models.CharField(max_length=50, verbose_name='备用字段')),
                ('LP16', models.CharField(max_length=50, verbose_name='备用字段')),
                ('LP17', models.CharField(max_length=50, verbose_name='备用字段')),
                ('LP18', models.CharField(max_length=50, verbose_name='备用字段')),
                ('LP19', models.CharField(max_length=50, verbose_name='备用字段')),
                ('LP20', models.CharField(max_length=50, verbose_name='备用字段一')),
            ],
            options={
                'verbose_name': '谷歌物流轨迹信息',
                'verbose_name_plural': '谷歌物流轨迹',
                'index_together': {('LP01', 'LP02', 'LP07', 'LP09')},
            },
        ),
    ]
