# Generated by Django 4.1.8 on 2024-06-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_logisticstrajectory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP05',
            field=models.CharField(max_length=50, verbose_name='行驶速度'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP06',
            field=models.CharField(max_length=50, verbose_name='行驶距离'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP07',
            field=models.CharField(max_length=50, verbose_name='行驶用时'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP08',
            field=models.CharField(max_length=50, verbose_name='抵达时间'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP09',
            field=models.CharField(max_length=400, verbose_name='终点经纬度'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP10',
            field=models.CharField(max_length=50, verbose_name='终点地址'),
        ),
    ]
