# Generated by Django 4.1.8 on 2024-06-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_logisticstrajectory_lp05_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP11',
            field=models.CharField(default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP12',
            field=models.CharField(default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP13',
            field=models.CharField(default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP14',
            field=models.CharField(default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP15',
            field=models.CharField(default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP16',
            field=models.CharField(default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP17',
            field=models.CharField(default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP18',
            field=models.CharField(default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP19',
            field=models.CharField(default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP20',
            field=models.CharField(default='', max_length=50, verbose_name='备用字段一'),
        ),
    ]
