# Generated by Django 4.1.8 on 2024-06-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_logisticstrajectory_lp11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP03',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='起点经度'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP04',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='起点地址'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP05',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='行驶速度'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP06',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='行驶距离'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP07',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='行驶用时'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP08',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='抵达时间'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP09',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='终点经纬度'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP10',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='终点地址'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP11',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP12',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP13',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP14',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP15',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP16',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP17',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP18',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP19',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段'),
        ),
        migrations.AlterField(
            model_name='logisticstrajectory',
            name='LP20',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段一'),
        ),
    ]
