# Generated by Django 4.1.8 on 2024-07-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_alter_logisticstrajectory_lp09_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wlglqx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LP01', models.CharField(max_length=50, verbose_name='功能代码')),
                ('LP02', models.CharField(max_length=50, verbose_name='功能名称')),
                ('LP03', models.CharField(blank=True, default='', max_length=50, verbose_name='功能级次')),
                ('LP04', models.CharField(blank=True, default='', max_length=400, verbose_name='启用标志')),
                ('LP05', models.CharField(blank=True, default='', max_length=50, verbose_name='顺序')),
                ('LP06', models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段')),
                ('LP07', models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段')),
                ('LP08', models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段')),
                ('LP09', models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段')),
                ('LP10', models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段')),
                ('LP11', models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段')),
                ('LP12', models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段')),
                ('LP13', models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段')),
                ('LP14', models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段')),
                ('LP15', models.CharField(blank=True, default='', max_length=50, verbose_name='备用字段一')),
            ],
            options={
                'verbose_name': '物流管理主界面',
                'verbose_name_plural': '物流管理主界面',
                'index_together': {('LP01', 'LP02')},
            },
        ),
    ]
